#!/usr/bin/env bash

# Update Nginx configuration to run as nginx user
sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf

# Update Nginx server block configuration to listen on port 8080 for all active IPs
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/conf.d/default.conf

# Test the Nginx configuration
nginx -t

# Restart Nginx service
service nginx restart
