#!/usr/bin/env bash
sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/conf.d/default.conf
nginx -t
service nginx restart
